FROM node:20 AS build

WORKDIR /app
COPY svelte.config.js vite.config.ts tsconfig.json ./
COPY package.json package-lock.json ./
RUN npm install
COPY static ./static
COPY src ./src
RUN npm run build


FROM node:20 as deploy

RUN apt-get update && apt-get install gnupg wget -y && \
    wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install google-chrome-stable -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
#needed for modules to work
COPY --from=build /app/package.json .

COPY --from=build /app/build .
CMD [ "node", "index.js" ]

