version: '3.9'
services:
  app-dev:
    build: .
    ports:
      - 5050:5173
      - 24678:24678
    volumes:
      - .:/app
      - /app/node_modules
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
    depends_on:
      - mongodb
volumes:
  mongo-data:
    driver: local
