version: '3.9'
services:
  backend:
    build: ./backend
    container_name: crawler-backend
    depends_on:
      - mongo
    expose:
      - 5000
    environment:
      - DATABASE_URL=mongodb://127.0.0.1:27017

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "./data/db:/data/db"

  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: always
    depends_on:
      - mongo
