FROM node:latest AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build


FROM node:latest as deploy

WORKDIR /app
#needed for modules to work
COPY --from=build /app/package.json .

COPY --from=build /app/build .
CMD [ "node", "index.js" ]

