db.auth("root", "password");
db = db.getSiblingDB("webapp");
db.createUser({
  user: "test",
  pwd: "test1234",
  roles: [{ role: "readWrite", db: "webapp" }],
});
db.createCollection("webpage_records", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: [
        "url",
        "periodicity",
        "regexp",
        "label",
        "active",
        "tags",
        "latestGroupId",
      ],
      additionalProperties: false,
      properties: {
        _id: {
          bsonType: "objectId",
        },
        url: {
          bsonType: "string",
          description: "must be a string and is required",
        },
        periodicity: {
          bsonType: "object",
          required: ["minutes", "hours", "days"],
          additionalProperties: false,
          properties: {
            minutes: {
              bsonType: "int",
              description: "must be an int and is required",
              minimum: 0,
            },
            hours: {
              bsonType: "int",
              description: "must be an int and is required",
              minimum: 0,
            },
            days: {
              bsonType: "int",
              description: "must be an int and is required",
              minimum: 0,
            },
          },
        },
        regexp: {
          bsonType: "string",
          description: "must be a string and is required",
        },
        label: {
          bsonType: "string",
          description: "must be a string and is required",
        },
        active: {
          bsonType: "bool",
          description: "must be a bool and is required",
        },
        tags: {
          bsonType: "array",
          items: {
            bsonType: "string",
          },
        },
        latestGroupId: {
          bsonType: "int",
          description: "must be an int and is required",
          minimum: -1,
        },
      },
    },
  },
});

db.webpage_records.insertMany([
  {
    url: "https://yawning-yam.com",
    periodicity: {
      minutes: 19,
      hours: 0,
      days: 7,
    },
    regexp: "Solutions",
    label: "westernise East Avon",
    active: false,
    tags: ["repurpose", "bootie", "indigo"],
    latestGroupId: 345,
  },
  {
    url: "https://female-emotion.com",
    periodicity: {
      minutes: 33,
      hours: 3,
      days: 12,
    },
    regexp: "pro",
    label: "Osmium",
    active: true,
    tags: ["Dynamic", "pink", "East"],
    latestGroupId: 229,
  },
  {
    url: "https://untidy-soundness.info",
    periodicity: {
      minutes: 25,
      hours: 23,
      days: 9,
    },
    regexp: "capability",
    label: "azure Producer Electronic",
    active: true,
    tags: ["blue", "Seamless", "likewise"],
    latestGroupId: 925,
  },
  {
    url: "https://striking-youth.com",
    periodicity: {
      minutes: 15,
      hours: 5,
      days: 14,
    },
    regexp: "withdrawal",
    label: "modi",
    active: false,
    tags: ["North", "Modern", "lest"],
    latestGroupId: 537,
  },
  {
    url: "https://elastic-glee.biz",
    periodicity: {
      minutes: 57,
      hours: 13,
      days: 0,
    },
    regexp: "orchid",
    label: "SMTP Producer",
    active: true,
    tags: ["corkscrew", "clinking", "bypassing"],
    latestGroupId: 451,
  },
  {
    url: "https://identical-lab.info",
    periodicity: {
      minutes: 25,
      hours: 23,
      days: 12,
    },
    regexp: "Androgyne",
    label: "female",
    active: false,
    tags: ["New", "Polynesia", "blue"],
    latestGroupId: 953,
  },
  {
    url: "http://glossy-tragedy.com",
    periodicity: {
      minutes: 38,
      hours: 22,
      days: 6,
    },
    regexp: "pink",
    label: "connecting impractical",
    active: true,
    tags: ["Devolved", "West", "Bridge"],
    latestGroupId: 175,
  },
  {
    url: "http://new-zoot-suit.info",
    periodicity: {
      minutes: 27,
      hours: 15,
      days: 4,
    },
    regexp: "shrimp",
    label: "wireless Rubber Product",
    active: true,
    tags: ["Samanta", "though", "black"],
    latestGroupId: 64,
  },
  {
    url: "http://cylindrical-shot.name",
    periodicity: {
      minutes: 17,
      hours: 9,
      days: 13,
    },
    regexp: "Architect",
    label: "meanwhile salmon",
    active: true,
    tags: ["Weymouth", "Northwest", "Outdoors"],
    latestGroupId: 377,
  },
  {
    url: "https://worthless-gift.info",
    periodicity: {
      minutes: 43,
      hours: 3,
      days: 0,
    },
    regexp: "South",
    label: "South shin Volvo",
    active: false,
    tags: ["maiores", "Planner", "Yemeni"],
    latestGroupId: 56,
  },
  {
    url: "http://giant-life.name",
    periodicity: {
      minutes: 35,
      hours: 21,
      days: 11,
    },
    regexp: "Pizza",
    label: "repair South",
    active: false,
    tags: ["Customer", "Bacon", "JBOD"],
    latestGroupId: 83,
  },
  {
    url: "https://regular-septicaemia.net",
    periodicity: {
      minutes: 58,
      hours: 13,
      days: 16,
    },
    regexp: "pish",
    label: "coalition visualize",
    active: true,
    tags: ["Oakland", "Music", "Communications"],
    latestGroupId: 331,
  },
  {
    url: "http://present-strife.com",
    periodicity: {
      minutes: 12,
      hours: 3,
      days: 17,
    },
    regexp: "black",
    label: "Bicycle Mouse sticky",
    active: true,
    tags: ["Jaron", "aw", "optimize"],
    latestGroupId: 836,
  },
  {
    url: "https://tasty-plover.biz",
    periodicity: {
      minutes: 37,
      hours: 0,
      days: 5,
    },
    regexp: "Avon",
    label: "monetize West Tome",
    active: true,
    tags: ["West", "Promethium", "Integration"],
    latestGroupId: 925,
  },
  {
    url: "http://eminent-pod.com",
    periodicity: {
      minutes: 22,
      hours: 19,
      days: 6,
    },
    regexp: "Frozen",
    label: "GB Northeast",
    active: true,
    tags: ["World", "Assistant", "SMS"],
    latestGroupId: 872,
  },
  {
    url: "https://elaborate-councilor.info",
    periodicity: {
      minutes: 26,
      hours: 15,
      days: 11,
    },
    regexp: "Trial",
    label: "bluetooth FTP",
    active: false,
    tags: ["Cruiser", "recontextualize", "Assurance"],
    latestGroupId: 870,
  },
  {
    url: "http://hairy-lunge.name",
    periodicity: {
      minutes: 25,
      hours: 1,
      days: 13,
    },
    regexp: "delay",
    label: "Computers set West",
    active: true,
    tags: ["Steel", "though", "blue"],
    latestGroupId: 27,
  },
  {
    url: "http://unrealistic-pantology.com",
    periodicity: {
      minutes: 28,
      hours: 23,
      days: 9,
    },
    regexp: "Antimony",
    label: "South North Roentgenium",
    active: true,
    tags: ["Southeast", "enable", "Lehi"],
    latestGroupId: 573,
  },
  {
    url: "http://treasured-shutdown.net",
    periodicity: {
      minutes: 22,
      hours: 17,
      days: 5,
    },
    regexp: "Credit",
    label: "SMS South Northwest",
    active: false,
    tags: ["reintermediate", "SCSI", "Senior"],
    latestGroupId: 150,
  },
  {
    url: "http://sarcastic-lead.biz",
    periodicity: {
      minutes: 59,
      hours: 18,
      days: 0,
    },
    regexp: "hard",
    label: "intranet",
    active: true,
    tags: ["Bedfordshire", "when", "Rhenium"],
    latestGroupId: 104,
  },
  {
    url: "http://offbeat-nectarine.org",
    periodicity: {
      minutes: 14,
      hours: 23,
      days: 24,
    },
    regexp: "female",
    label: "Directives",
    active: true,
    tags: ["1080p", "Austin", "Southeast"],
    latestGroupId: 680,
  },
  {
    url: "https://melodic-variability.name",
    periodicity: {
      minutes: 49,
      hours: 2,
      days: 10,
    },
    regexp: "consequently",
    label: "Electric",
    active: false,
    tags: ["thrifty", "Rupee", "Account"],
    latestGroupId: 761,
  },
  {
    url: "https://spicy-menu.net",
    periodicity: {
      minutes: 44,
      hours: 12,
      days: 20,
    },
    regexp: "COM",
    label: "Netherlands purple SMTP",
    active: true,
    tags: ["Borders", "Ball", "Southeast"],
    latestGroupId: 833,
  },
  {
    url: "http://wavy-netsuke.name",
    periodicity: {
      minutes: 46,
      hours: 15,
      days: 5,
    },
    regexp: "hertz",
    label: "Cheese Leila Checking",
    active: false,
    tags: ["Olympia", "Norman", "Buckinghamshire"],
    latestGroupId: 100,
  },
  {
    url: "https://buzzing-radio.info",
    periodicity: {
      minutes: 54,
      hours: 1,
      days: 0,
    },
    regexp: "suddenly",
    label: "non",
    active: false,
    tags: ["coulomb", "Meadow", "Northwest"],
    latestGroupId: 811,
  },
  {
    url: "http://jagged-wallaby.net",
    periodicity: {
      minutes: 34,
      hours: 17,
      days: 3,
    },
    regexp: "intent",
    label: "amidst bluetooth wrestle",
    active: true,
    tags: ["Yuba", "experiences", "connecting"],
    latestGroupId: 918,
  },
  {
    url: "https://skeletal-nectarine.org",
    periodicity: {
      minutes: 20,
      hours: 19,
      days: 22,
    },
    regexp: "nihil",
    label: "despite",
    active: false,
    tags: ["Metal", "coulomb", "invoice"],
    latestGroupId: 263,
  },
  {
    url: "https://poised-recall.net",
    periodicity: {
      minutes: 19,
      hours: 3,
      days: 7,
    },
    regexp: "interfaces",
    label: "deliberately Lesotho Peso",
    active: true,
    tags: ["Texas", "Southeast", "blue"],
    latestGroupId: 563,
  },
  {
    url: "http://quintessential-deathwatch.org",
    periodicity: {
      minutes: 20,
      hours: 6,
      days: 21,
    },
    regexp: "Promethium",
    label: "Electronic bypassing",
    active: true,
    tags: ["fluid", "generating", "Mandatory"],
    latestGroupId: 521,
  },
  {
    url: "http://metallic-nestmate.com",
    periodicity: {
      minutes: 58,
      hours: 14,
      days: 25,
    },
    regexp: "asymmetric",
    label: "loyal",
    active: false,
    tags: ["Steel", "Hawaii", "Mouse"],
    latestGroupId: 883,
  },
  {
    url: "http://broken-horst.org",
    periodicity: {
      minutes: 43,
      hours: 5,
      days: 6,
    },
    regexp: "neutral",
    label: "Berkshire",
    active: false,
    tags: ["indigo", "after", "Internal"],
    latestGroupId: 891,
  },
  {
    url: "http://lonely-tog.com",
    periodicity: {
      minutes: 4,
      hours: 4,
      days: 2,
    },
    regexp: "Squares",
    label: "Northeast",
    active: false,
    tags: ["behind", "whereas", "architecture"],
    latestGroupId: 889,
  },
  {
    url: "http://boiling-son.net",
    periodicity: {
      minutes: 56,
      hours: 11,
      days: 27,
    },
    regexp: "Cab",
    label: "female Tuna",
    active: false,
    tags: ["cultivate", "Wyoming", "Communications"],
    latestGroupId: 509,
  },
  {
    url: "http://haunting-rod.org",
    periodicity: {
      minutes: 49,
      hours: 17,
      days: 18,
    },
    regexp: "paradigms",
    label: "Gasoline incarcerate",
    active: false,
    tags: ["bah", "orchid", "generation"],
    latestGroupId: 702,
  },
  {
    url: "https://unlined-ruckus.info",
    periodicity: {
      minutes: 4,
      hours: 20,
      days: 14,
    },
    regexp: "teal",
    label: "District programming Porsche",
    active: true,
    tags: ["channels", "Keyboard", "sievert"],
    latestGroupId: 211,
  },
  {
    url: "https://entire-scratch.com",
    periodicity: {
      minutes: 35,
      hours: 15,
      days: 16,
    },
    regexp: "Account",
    label: "orchid",
    active: true,
    tags: ["boohoo", "ROI", "female"],
    latestGroupId: 14,
  },
  {
    url: "https://tall-decency.net",
    periodicity: {
      minutes: 21,
      hours: 7,
      days: 17,
    },
    regexp: "Redding",
    label: "Diesel male Reduced",
    active: true,
    tags: ["rem", "Montana", "Americium"],
    latestGroupId: 40,
  },
  {
    url: "http://colossal-clone.org",
    periodicity: {
      minutes: 49,
      hours: 15,
      days: 29,
    },
    regexp: "Outdoors",
    label: "yellow Designer Gasoline",
    active: false,
    tags: ["target", "Ouguiya", "Borders"],
    latestGroupId: 647,
  },
  {
    url: "https://nutritious-nonbeliever.biz",
    periodicity: {
      minutes: 56,
      hours: 1,
      days: 25,
    },
    regexp: "besides",
    label: "Bike",
    active: true,
    tags: ["transmit", "Zirconium", "Afghani"],
    latestGroupId: 844,
  },
  {
    url: "https://sweet-omnivore.com",
    periodicity: {
      minutes: 25,
      hours: 0,
      days: 16,
    },
    regexp: "transmit",
    label: "Future near",
    active: false,
    tags: ["pate", "Van", "IP"],
    latestGroupId: 944,
  },
  {
    url: "https://trusty-tourist.net",
    periodicity: {
      minutes: 58,
      hours: 11,
      days: 16,
    },
    regexp: "Awesome",
    label: "along Sacramento Bronze",
    active: false,
    tags: ["Luxurious", "above", "Fresh"],
    latestGroupId: 869,
  },
  {
    url: "https://tough-pray.info",
    periodicity: {
      minutes: 47,
      hours: 0,
      days: 22,
    },
    regexp: "Liaison",
    label: "Rutherfordium Spring",
    active: false,
    tags: ["paradigm", "Luxurious", "XML"],
    latestGroupId: 139,
  },
  {
    url: "http://sarcastic-bathhouse.info",
    periodicity: {
      minutes: 18,
      hours: 3,
      days: 0,
    },
    regexp: "copying",
    label: "Finland",
    active: true,
    tags: ["Coordinator", "Delaware", "Frozen"],
    latestGroupId: 192,
  },
  {
    url: "https://official-brooch.info",
    periodicity: {
      minutes: 10,
      hours: 6,
      days: 7,
    },
    regexp: "Steel",
    label: "Shilling envisioneer",
    active: true,
    tags: ["Engineer", "Fresh", "Refined"],
    latestGroupId: 743,
  },
  {
    url: "https://flowery-plagiarism.info",
    periodicity: {
      minutes: 14,
      hours: 22,
      days: 19,
    },
    regexp: "quos",
    label: "indexing Avon Salvador",
    active: true,
    tags: ["withdrawal", "Polarised", "index"],
    latestGroupId: 367,
  },
  {
    url: "http://mixed-depressive.name",
    periodicity: {
      minutes: 9,
      hours: 14,
      days: 12,
    },
    regexp: "Human",
    label: "the pink Chief",
    active: true,
    tags: ["viral", "Audi", "input"],
    latestGroupId: 299,
  },
  {
    url: "http://scrawny-vivo.info",
    periodicity: {
      minutes: 12,
      hours: 17,
      days: 28,
    },
    regexp: "repentant",
    label: "Tuna",
    active: true,
    tags: ["Uruguayo", "Northeast", "City"],
    latestGroupId: 58,
  },
  {
    url: "https://klutzy-snorer.org",
    periodicity: {
      minutes: 56,
      hours: 20,
      days: 27,
    },
    regexp: "Chevrolet",
    label: "Berkshire bypass",
    active: true,
    tags: ["pink", "Classical", "Shoes"],
    latestGroupId: 499,
  },
  {
    url: "https://insignificant-plate.info",
    periodicity: {
      minutes: 42,
      hours: 17,
      days: 24,
    },
    regexp: "Polestar",
    label: "Hampshire",
    active: false,
    tags: ["white", "Toys", "after"],
    latestGroupId: 926,
  },
  {
    url: "https://violet-swamp.com",
    periodicity: {
      minutes: 41,
      hours: 19,
      days: 27,
    },
    regexp: "Wooden",
    label: "Naira Freeway",
    active: true,
    tags: ["est", "Tactics", "Music"],
    latestGroupId: 665,
  },
  {
    url: "https://deadly-top-hat.info",
    periodicity: {
      minutes: 9,
      hours: 7,
      days: 9,
    },
    regexp: "Niger",
    label: "Electric Books South",
    active: false,
    tags: ["Cheese", "deposit", "East"],
    latestGroupId: 781,
  },
  {
    url: "https://leafy-election.name",
    periodicity: {
      minutes: 6,
      hours: 4,
      days: 25,
    },
    regexp: "matrix",
    label: "innovative Coupe North",
    active: false,
    tags: ["Developer", "Electronic", "Forges"],
    latestGroupId: 798,
  },
  {
    url: "http://tart-balalaika.biz",
    periodicity: {
      minutes: 39,
      hours: 20,
      days: 30,
    },
    regexp: "City",
    label: "AI North",
    active: true,
    tags: ["dynamic", "Soul", "female"],
    latestGroupId: 340,
  },
  {
    url: "http://uncommon-onion.info",
    periodicity: {
      minutes: 21,
      hours: 1,
      days: 20,
    },
    regexp: "Non",
    label: "attitude Pasco West",
    active: true,
    tags: ["Electronics", "IB", "Enhanced"],
    latestGroupId: 412,
  },
  {
    url: "https://plaintive-cue.net",
    periodicity: {
      minutes: 54,
      hours: 2,
      days: 1,
    },
    regexp: "henry",
    label: "Lead Lawton deliver",
    active: false,
    tags: ["XSS", "Demiflux", "Product"],
    latestGroupId: 732,
  },
  {
    url: "http://half-finger.com",
    periodicity: {
      minutes: 3,
      hours: 5,
      days: 27,
    },
    regexp: "Cambridgeshire",
    label: "Hatchback impedit Coupe",
    active: false,
    tags: ["Shoes", "Account", "suspicious"],
    latestGroupId: 408,
  },
  {
    url: "https://keen-policeman.name",
    periodicity: {
      minutes: 51,
      hours: 17,
      days: 28,
    },
    regexp: "loyally",
    label: "synthesize launder navigating",
    active: false,
    tags: ["Salad", "sexy", "Southwest"],
    latestGroupId: 217,
  },
  {
    url: "http://delayed-fishnet.com",
    periodicity: {
      minutes: 35,
      hours: 17,
      days: 24,
    },
    regexp: "compressing",
    label: "indeed",
    active: false,
    tags: ["fat", "panel", "East"],
    latestGroupId: 701,
  },
  {
    url: "https://crowded-hatchling.com",
    periodicity: {
      minutes: 25,
      hours: 15,
      days: 19,
    },
    regexp: "across",
    label: "Electric Berkshire",
    active: false,
    tags: ["Orlando", "Crossroad", "Gibraltar"],
    latestGroupId: 826,
  },
  {
    url: "http://miniature-stir-fry.com",
    periodicity: {
      minutes: 51,
      hours: 12,
      days: 14,
    },
    regexp: "payment",
    label: "Southwest Shirt Van",
    active: true,
    tags: ["pfft", "West", "Bentley"],
    latestGroupId: 756,
  },
  {
    url: "http://bubbly-mud.net",
    periodicity: {
      minutes: 53,
      hours: 20,
      days: 17,
    },
    regexp: "jostle",
    label: "West Creative",
    active: true,
    tags: ["Diesel", "Legacy", "duh"],
    latestGroupId: 500,
  },
  {
    url: "http://honest-coal.name",
    periodicity: {
      minutes: 28,
      hours: 22,
      days: 19,
    },
    regexp: "payment",
    label: "Androgynous",
    active: true,
    tags: ["Market", "lime", "quirkily"],
    latestGroupId: 341,
  },
  {
    url: "http://svelte-crime.name",
    periodicity: {
      minutes: 48,
      hours: 9,
      days: 8,
    },
    regexp: "Cadillac",
    label: "Southwest set",
    active: false,
    tags: ["services", "whereas", "vortals"],
    latestGroupId: 735,
  },
  {
    url: "https://delectable-leveret.name",
    periodicity: {
      minutes: 56,
      hours: 9,
      days: 28,
    },
    regexp: "Cheese",
    label: "male payment West",
    active: false,
    tags: ["now", "gosh", "EXE"],
    latestGroupId: 855,
  },
  {
    url: "https://gruesome-saviour.name",
    periodicity: {
      minutes: 52,
      hours: 4,
      days: 17,
    },
    regexp: "ivory",
    label: "Metal laudantium",
    active: true,
    tags: ["venture", "virtual", "neural"],
    latestGroupId: 298,
  },
  {
    url: "http://outlying-chopstick.com",
    periodicity: {
      minutes: 12,
      hours: 20,
      days: 11,
    },
    regexp: "overriding",
    label: "Indium OCR kilogram",
    active: true,
    tags: ["needily", "Metal", "Grocery"],
    latestGroupId: 954,
  },
  {
    url: "http://minty-reindeer.net",
    periodicity: {
      minutes: 4,
      hours: 14,
      days: 29,
    },
    regexp: "payment",
    label: "sievert whether",
    active: false,
    tags: ["Hatchback", "Swedish", "Throughway"],
    latestGroupId: 256,
  },
  {
    url: "https://deep-accusation.biz",
    periodicity: {
      minutes: 6,
      hours: 17,
      days: 9,
    },
    regexp: "BMX",
    label: "Texas International Convertible",
    active: true,
    tags: ["orchid", "copy", "Account"],
    latestGroupId: 928,
  },
  {
    url: "https://whispered-reorganisation.name",
    periodicity: {
      minutes: 53,
      hours: 7,
      days: 24,
    },
    regexp: "Account",
    label: "Steel",
    active: false,
    tags: ["male", "optimizing", "Unbranded"],
    latestGroupId: 114,
  },
  {
    url: "https://first-phrasing.info",
    periodicity: {
      minutes: 23,
      hours: 10,
      days: 18,
    },
    regexp: "est",
    label: "Chips Communications",
    active: false,
    tags: ["Berkshire", "microchip", "Principal"],
    latestGroupId: 650,
  },
  {
    url: "http://puzzled-armpit.net",
    periodicity: {
      minutes: 4,
      hours: 21,
      days: 3,
    },
    regexp: "Intelligent",
    label: "crown Trial",
    active: true,
    tags: ["invoice", "Schiller", "Strategist"],
    latestGroupId: 279,
  },
  {
    url: "https://pleasing-wire.name",
    periodicity: {
      minutes: 28,
      hours: 6,
      days: 22,
    },
    regexp: "Smart",
    label: "evolve",
    active: false,
    tags: ["Seychelles", "Steel", "Customer"],
    latestGroupId: 760,
  },
  {
    url: "http://anguished-necklace.biz",
    periodicity: {
      minutes: 44,
      hours: 6,
      days: 29,
    },
    regexp: "Lempira",
    label: "Pizza Assistant",
    active: false,
    tags: ["pale", "Supervisor", "Mobility"],
    latestGroupId: 117,
  },
  {
    url: "http://negative-general.biz",
    periodicity: {
      minutes: 34,
      hours: 19,
      days: 7,
    },
    regexp: "sandblast",
    label: "Cab",
    active: true,
    tags: ["Forward", "quantify", "Convertible"],
    latestGroupId: 164,
  },
  {
    url: "https://original-stot.info",
    periodicity: {
      minutes: 9,
      hours: 5,
      days: 27,
    },
    regexp: "content",
    label: "Ball Bigender",
    active: false,
    tags: ["Overpass", "Mobility", "Porsche"],
    latestGroupId: 512,
  },
  {
    url: "http://imperturbable-airship.net",
    periodicity: {
      minutes: 28,
      hours: 21,
      days: 0,
    },
    regexp: "Hatchback",
    label: "Niue",
    active: true,
    tags: ["Liberia", "ugh", "bypassing"],
    latestGroupId: 430,
  },
  {
    url: "http://scornful-boysenberry.org",
    periodicity: {
      minutes: 6,
      hours: 11,
      days: 12,
    },
    regexp: "Developer",
    label: "stunt Minivan North",
    active: true,
    tags: ["Lesotho", "Hybrid", "Markets"],
    latestGroupId: 299,
  },
  {
    url: "https://frightened-townhouse.info",
    periodicity: {
      minutes: 15,
      hours: 5,
      days: 3,
    },
    regexp: "Yttrium",
    label: "Granite Chief",
    active: false,
    tags: ["parallelism", "Northeast", "Account"],
    latestGroupId: 974,
  },
  {
    url: "https://mindless-camera.net",
    periodicity: {
      minutes: 34,
      hours: 0,
      days: 19,
    },
    regexp: "pixel",
    label: "Accountability cyan",
    active: false,
    tags: ["systematic", "sexy", "Gasoline"],
    latestGroupId: 72,
  },
  {
    url: "http://elaborate-insert.com",
    periodicity: {
      minutes: 11,
      hours: 7,
      days: 12,
    },
    regexp: "Pickup",
    label: "quia transmitter",
    active: true,
    tags: ["hacking", "Gasoline", "Manager"],
    latestGroupId: 348,
  },
  {
    url: "http://forceful-delight.name",
    periodicity: {
      minutes: 2,
      hours: 11,
      days: 27,
    },
    regexp: "programming",
    label: "teal Funk Table",
    active: true,
    tags: ["Gloves", "Berkshire", "yellow"],
    latestGroupId: 248,
  },
  {
    url: "https://crisp-emanate.info",
    periodicity: {
      minutes: 5,
      hours: 8,
      days: 25,
    },
    regexp: "Maine",
    label: "HTTP",
    active: false,
    tags: ["Bypass", "Rover", "Industrial"],
    latestGroupId: 880,
  },
  {
    url: "https://trustworthy-defense.com",
    periodicity: {
      minutes: 28,
      hours: 14,
      days: 18,
    },
    regexp: "keel",
    label: "Toyota",
    active: true,
    tags: ["bandwidth", "SDD", "Coordinator"],
    latestGroupId: 248,
  },
  {
    url: "http://ornate-permit.net",
    periodicity: {
      minutes: 0,
      hours: 9,
      days: 17,
    },
    regexp: "Ford",
    label: "Transexual website",
    active: true,
    tags: ["Southeast", "trivialise", "Diesel"],
    latestGroupId: 68,
  },
  {
    url: "http://sneaky-sailor.com",
    periodicity: {
      minutes: 35,
      hours: 10,
      days: 23,
    },
    regexp: "Rap",
    label: "Account",
    active: false,
    tags: ["benchmark", "Buffalo", "turquoise"],
    latestGroupId: 139,
  },
  {
    url: "https://writhing-gerbil.com",
    periodicity: {
      minutes: 39,
      hours: 0,
      days: 17,
    },
    regexp: "empower",
    label: "female gee",
    active: false,
    tags: ["roughly", "superstructure", "Egypt"],
    latestGroupId: 837,
  },
  {
    url: "http://agitated-paperback.com",
    periodicity: {
      minutes: 20,
      hours: 0,
      days: 22,
    },
    regexp: "Northwest",
    label: "Intranet Ferrari lime",
    active: true,
    tags: ["Gloves", "Indiana", "red"],
    latestGroupId: 691,
  },
  {
    url: "https://lovely-event.net",
    periodicity: {
      minutes: 30,
      hours: 19,
      days: 28,
    },
    regexp: "Luxurious",
    label: "Strategist Forward",
    active: false,
    tags: ["Sedan", "Arkansas", "man"],
    latestGroupId: 661,
  },
  {
    url: "http://normal-weekender.com",
    periodicity: {
      minutes: 12,
      hours: 18,
      days: 28,
    },
    regexp: "Minivan",
    label: "Mouse Rufiyaa black",
    active: false,
    tags: ["Vermont", "Technician", "exercitationem"],
    latestGroupId: 474,
  },
  {
    url: "http://real-soul.com",
    periodicity: {
      minutes: 11,
      hours: 14,
      days: 26,
    },
    regexp: "Touring",
    label: "Blues Legacy",
    active: true,
    tags: ["West", "Practical", "parse"],
    latestGroupId: 465,
  },
  {
    url: "https://extra-large-bather.net",
    periodicity: {
      minutes: 34,
      hours: 14,
      days: 12,
    },
    regexp: "Samarium",
    label: "SMTP",
    active: true,
    tags: ["teal", "niches", "Mountain"],
    latestGroupId: 60,
  },
  {
    url: "http://superb-oregano.org",
    periodicity: {
      minutes: 50,
      hours: 3,
      days: 16,
    },
    regexp: "Well",
    label: "alarm female",
    active: false,
    tags: ["East", "Sharable", "olive"],
    latestGroupId: 297,
  },
  {
    url: "http://half-cookie.org",
    periodicity: {
      minutes: 53,
      hours: 22,
      days: 19,
    },
    regexp: "deposit",
    label: "Bedfordshire payment South",
    active: false,
    tags: ["East", "Southeast", "Cambridgeshire"],
    latestGroupId: 90,
  },
  {
    url: "https://adored-stonework.biz",
    periodicity: {
      minutes: 4,
      hours: 13,
      days: 24,
    },
    regexp: "South",
    label: "Investment Roentgenium Berkshire",
    active: true,
    tags: ["plus", "Senegal", "Van"],
    latestGroupId: 340,
  },
  {
    url: "http://naive-analytics.info",
    periodicity: {
      minutes: 20,
      hours: 5,
      days: 10,
    },
    regexp: "steradian",
    label: "Frozen",
    active: false,
    tags: ["Electronics", "Oriental", "BMX"],
    latestGroupId: 915,
  },
  {
    url: "http://jam-packed-hive.net",
    periodicity: {
      minutes: 17,
      hours: 3,
      days: 21,
    },
    regexp: "magni",
    label: "Corporate Bronze Cruiser",
    active: false,
    tags: ["Cheese", "female", "Other"],
    latestGroupId: 487,
  },
  {
    url: "https://orange-farming.net",
    periodicity: {
      minutes: 42,
      hours: 3,
      days: 10,
    },
    regexp: "blue",
    label: "matrix And",
    active: true,
    tags: ["Pitcairn", "calculating", "SAS"],
    latestGroupId: 384,
  },
  {
    url: "http://handy-contrail.biz",
    periodicity: {
      minutes: 38,
      hours: 10,
      days: 26,
    },
    regexp: "blue",
    label: "Future Computers North",
    active: true,
    tags: ["Dynamic", "Bronze", "on"],
    latestGroupId: 702,
  },
  {
    url: "http://sorrowful-commander.org",
    periodicity: {
      minutes: 4,
      hours: 18,
      days: 23,
    },
    regexp: "Tokelau",
    label: "bifurcated clank",
    active: false,
    tags: ["Electric", "as", "Bicycle"],
    latestGroupId: 438,
  },
  {
    url: "https://robust-communication.net",
    periodicity: {
      minutes: 7,
      hours: 14,
      days: 29,
    },
    regexp: "Wisconsin",
    label: "Chicken backing Creative",
    active: false,
    tags: ["Engineer", "North", "Fresh"],
    latestGroupId: 902,
  },
]);

db.createCollection("executions", {
  validator: {
    $jsonSchema: {
      bsonType: "object",
      required: [
        "ownerId",
        "groupId",
        "root",
        "url",
        "crawlTimeStart",
        "crawlTimeEnd",
        "status",
        "sitesCrawled",
        "links",
        "title",
      ],
      additionalProperties: false,
      properties: {
        _id: {
          bsonType: "objectId",
        },
        ownerId: {
          bsonType: "objectId",
          description: "must be an ObjectId and is required",
        },
        groupId: {
          bsonType: "int",
          description: "must be an int and is required",
        },
        root: {
          bsonType: "bool",
          description: "must be a bool and is required",
        },
        url: {
          bsonType: "string",
          description: "must be a string and is required",
        },
        crawlTimeStart: {
          bsonType: "long",
          description: "must be an int and is required",
        },
        crawlTimeEnd: {
          bsonType: "long",
          description: "must be an int and is required",
        },
        status: {
          bsonType: "string",
          enum: ["success", "failed", "running"],
          description:
            'must be one of "success", "failed", or "running" and is required',
        },
        sitesCrawled: {
          bsonType: "int",
          minimum: 0,
          description: "must be a non-negative integer and is required",
        },
        links: {
          bsonType: "array",
          items: {
            bsonType: "string",
          },
          description: "must be an array of strings",
        },
        title: {
          bsonType: "string",
          description: "must be a string and is required",
        },
      },
    },
  },
});

db.executions.insertMany([
  {
    ownerId: ObjectId("0c0b366987bb7eed7d17d62a"),
    groupId: 73696,
    root: true,
    url: "https://gleaming-cinnamon.info",
    crawlTimeStart: Long(1661561222172),
    crawlTimeEnd: Long(1674199488589),
    status: "running",
    sitesCrawled: 63651,
    links: [
      "https://pesky-mandate.biz",
      "https://blissful-means.com",
      "https://incompatible-clarification.org",
      "http://worried-yellowjacket.name",
      "https://paltry-extreme.info",
      "https://remorseful-north.org",
    ],
    title: "beatae aspernatur architecto",
  },
  {
    ownerId: ObjectId("d45cfbbbfaf640873dc1eeb6"),
    groupId: 74193,
    root: false,
    url: "http://whopping-dill.com",
    crawlTimeStart: Long(1668494215279),
    crawlTimeEnd: Long(1691916266913),
    status: "success",
    sitesCrawled: 88106,
    links: [
      "https://nutritious-congress.biz",
      "http://square-sorghum.net",
      "http://impractical-gumshoe.biz",
      "https://unkempt-insulation.biz",
      "http://acidic-chili.com",
      "https://scary-resistance.org",
      "https://pointed-minister.com",
      "https://timely-reject.info",
      "http://cheap-hope.com",
      "https://next-onset.name",
    ],
    title: "corrupti nemo necessitatibus",
  },
  {
    ownerId: ObjectId("9c9c3a7df6ab2c126f0db0e0"),
    groupId: 34536,
    root: false,
    url: "http://second-scheduling.com",
    crawlTimeStart: Long(1649429790756),
    crawlTimeEnd: Long(1682877109979),
    status: "success",
    sitesCrawled: 99212,
    links: [
      "https://dense-pansy.org",
      "https://required-bandolier.com",
      "http://lanky-journalist.info",
      "http://satisfied-journal.name",
      "https://creative-app.com",
      "https://joyful-importance.net",
      "https://supportive-sole.biz",
      "http://muffled-emergence.org",
      "http://emotional-thongs.net",
    ],
    title: "eveniet quam quisquam",
  },
  {
    ownerId: ObjectId("c2fa51e8f39fae005c8e708b"),
    groupId: 88705,
    root: false,
    url: "http://gray-welfare.biz",
    crawlTimeStart: Long(1659827558463),
    crawlTimeEnd: Long(1689817777378),
    status: "success",
    sitesCrawled: 44354,
    links: [
      "https://reckless-orangutan.org",
      "https://frigid-compass.net",
      "http://safe-mambo.com",
      "http://odd-marsh.net",
      "http://personal-rhythm.info",
      "http://bossy-revitalisation.net",
      "http://well-documented-mailman.org",
      "http://tattered-stop.net",
    ],
    title: "qui aliquam recusandae",
  },
  {
    ownerId: ObjectId("d8da55dff0afa59adb012aa6"),
    groupId: 28339,
    root: true,
    url: "http://immense-skullduggery.info",
    crawlTimeStart: Long(1647201381831),
    crawlTimeEnd: Long(1681032754446),
    status: "failed",
    sitesCrawled: 16924,
    links: [
      "https://charming-arithmetic.org",
      "https://able-lycra.com",
      "https://mellow-gasket.net",
      "https://nautical-candy.org",
      "https://appropriate-legislator.name",
      "https://tubby-someone.biz",
    ],
    title: "rem officiis accusantium",
  },
  {
    ownerId: ObjectId("cad8dc9f540a66c6ab7c3a2a"),
    groupId: 63082,
    root: true,
    url: "https://heartfelt-land.com",
    crawlTimeStart: Long(1654635006927),
    crawlTimeEnd: Long(1684836304503),
    status: "running",
    sitesCrawled: 86120,
    links: [
      "http://graceful-neon.com",
      "http://few-grandfather.biz",
      "http://new-homicide.name",
    ],
    title: "consequuntur ullam odit",
  },
  {
    ownerId: ObjectId("126d57fbd4d8ace00bceeb5c"),
    groupId: 87428,
    root: false,
    url: "http://entire-icebreaker.info",
    crawlTimeStart: Long(1667802850397),
    crawlTimeEnd: Long(1674543933058),
    status: "success",
    sitesCrawled: 75616,
    links: [
      "https://exotic-construction.org",
      "https://profuse-outset.org",
      "http://flashy-developer.net",
      "https://weekly-singing.info",
      "http://avaricious-retrospectivity.name",
      "https://trusty-tank.biz",
    ],
    title: "commodi a quibusdam",
  },
  {
    ownerId: ObjectId("68a5dfe1d5a4ce3d4ed16d30"),
    groupId: 77777,
    root: false,
    url: "http://unwilling-rail.net",
    crawlTimeStart: Long(1658374033587),
    crawlTimeEnd: Long(1692870894223),
    status: "failed",
    sitesCrawled: 46545,
    links: [
      "https://carefree-tile.biz",
      "https://blind-sucker.biz",
      "https://equatorial-vase.name",
    ],
    title: "sed eum voluptate",
  },
  {
    ownerId: ObjectId("a50d0caaeb73a08ff8ab0122"),
    groupId: 90209,
    root: false,
    url: "https://dimwitted-vet.org",
    crawlTimeStart: Long(1642169946102),
    crawlTimeEnd: Long(1686937033822),
    status: "running",
    sitesCrawled: 22851,
    links: ["https://noted-trolley.com", "https://international-printing.com"],
    title: "dolor occaecati sunt",
  },
  {
    ownerId: ObjectId("1bfbdabcf8b52289fd2ed18d"),
    groupId: 26007,
    root: false,
    url: "https://kindly-employer.biz",
    crawlTimeStart: Long(1649442045122),
    crawlTimeEnd: Long(1674180866207),
    status: "success",
    sitesCrawled: 52361,
    links: [
      "http://unusual-passenger.name",
      "https://quick-witted-adulthood.net",
      "https://lame-pavilion.net",
      "https://vague-union.net",
      "http://untried-dancer.name",
      "https://far-gloom.info",
      "https://shocked-snorer.biz",
    ],
    title: "iste magni rem",
  },
  {
    ownerId: ObjectId("6dfac515448ef0abafff9d4b"),
    groupId: 44341,
    root: true,
    url: "https://tidy-ritual.com",
    crawlTimeStart: Long(1644700184878),
    crawlTimeEnd: Long(1677541973928),
    status: "success",
    sitesCrawled: 93593,
    links: [],
    title: "dolor assumenda ipsa",
  },
  {
    ownerId: ObjectId("a8ffb390f7c5affe7cfac7ed"),
    groupId: 36204,
    root: true,
    url: "http://closed-gastropod.biz",
    crawlTimeStart: Long(1660150064624),
    crawlTimeEnd: Long(1687559779870),
    status: "running",
    sitesCrawled: 80578,
    links: [
      "https://definite-location.info",
      "https://regal-sideboard.net",
      "http://potable-pleasure.name",
      "http://important-hosiery.name",
      "https://next-airmail.info",
      "https://babyish-pajamas.org",
      "https://blaring-impostor.info",
      "http://worst-control.com",
      "http://enchanting-construction.net",
      "http://lumpy-denim.com",
    ],
    title: "iure iure quidem",
  },
  {
    ownerId: ObjectId("deca2ce0fbebbebcf2a038b6"),
    groupId: 23663,
    root: true,
    url: "http://square-plaster.info",
    crawlTimeStart: Long(1647811075456),
    crawlTimeEnd: Long(1681820597485),
    status: "running",
    sitesCrawled: 19254,
    links: ["https://uncommon-prevalence.info"],
    title: "repellendus doloribus eum",
  },
  {
    ownerId: ObjectId("adea2af4f37e73afe73ec5be"),
    groupId: 11525,
    root: false,
    url: "https://tiny-dory.com",
    crawlTimeStart: Long(1667487933620),
    crawlTimeEnd: Long(1692609557698),
    status: "running",
    sitesCrawled: 16132,
    links: [
      "https://scrawny-tentacle.org",
      "https://tragic-prow.net",
      "https://lazy-park.name",
      "http://classic-skiing.biz",
      "http://taut-corn.info",
      "https://inborn-pod.com",
      "http://spicy-tabletop.info",
    ],
    title: "debitis quae mollitia",
  },
  {
    ownerId: ObjectId("a49f7eea0a3c8dac8c3a06e7"),
    groupId: 92084,
    root: false,
    url: "http://everlasting-blank.net",
    crawlTimeStart: Long(1671235082452),
    crawlTimeEnd: Long(1683350576248),
    status: "running",
    sitesCrawled: 646,
    links: [
      "http://miniature-semantics.name",
      "http://adorable-colonisation.org",
      "http://confused-puritan.net",
      "https://wry-marketing.com",
      "https://euphoric-analog.org",
      "https://strident-choker.com",
      "http://wild-schoolhouse.net",
    ],
    title: "maxime laudantium eum",
  },
  {
    ownerId: ObjectId("8ac9baabaabd7e0355cedf78"),
    groupId: 40750,
    root: true,
    url: "http://incomplete-hunting.com",
    crawlTimeStart: Long(1651784992459),
    crawlTimeEnd: Long(1676513733801),
    status: "running",
    sitesCrawled: 90507,
    links: [
      "https://filthy-meet.org",
      "https://half-seabass.info",
      "http://cavernous-coordinator.biz",
      "http://unlawful-island.net",
      "http://harmonious-thread.com",
    ],
    title: "nostrum possimus tempora",
  },
  {
    ownerId: ObjectId("6da061fbaacabe2d3f3381c1"),
    groupId: 85282,
    root: false,
    url: "http://practical-chair.com",
    crawlTimeStart: Long(1646515294906),
    crawlTimeEnd: Long(1679839033617),
    status: "running",
    sitesCrawled: 34732,
    links: [],
    title: "accusantium quo quisquam",
  },
  {
    ownerId: ObjectId("cb1a1dba37cfeddb4aeec80a"),
    groupId: 81364,
    root: true,
    url: "https://extroverted-dreamer.org",
    crawlTimeStart: Long(1642173309924),
    crawlTimeEnd: Long(1684569502054),
    status: "running",
    sitesCrawled: 41736,
    links: [
      "http://fitting-stucco.net",
      "https://minor-race.info",
      "https://swift-messenger.net",
    ],
    title: "inventore distinctio delectus",
  },
  {
    ownerId: ObjectId("fccf4556f76bf14fb3ffee1c"),
    groupId: 95429,
    root: false,
    url: "http://metallic-crewmate.name",
    crawlTimeStart: Long(1641009543587),
    crawlTimeEnd: Long(1686303703331),
    status: "running",
    sitesCrawled: 47308,
    links: [
      "http://organic-advocate.org",
      "https://glorious-regulator.biz",
      "https://formal-verve.com",
      "https://vague-hepatitis.com",
      "http://opulent-fortune.net",
      "https://both-classmate.info",
      "http://surprised-drawbridge.org",
    ],
    title: "rem est perspiciatis",
  },
  {
    ownerId: ObjectId("ed5dce4acc4f9abcb42cb08a"),
    groupId: 52298,
    root: false,
    url: "https://babyish-aluminum.biz",
    crawlTimeStart: Long(1669210616759),
    crawlTimeEnd: Long(1678382902686),
    status: "success",
    sitesCrawled: 95618,
    links: [
      "http://upset-cigarette.net",
      "http://thoughtful-bunghole.com",
      "http://grown-spokesman.net",
      "http://sharp-tavern.net",
      "http://friendly-empire.name",
    ],
    title: "tempore officiis cupiditate",
  },
  {
    ownerId: ObjectId("ce8368b1ccb07d9a5bdaae29"),
    groupId: 64322,
    root: false,
    url: "https://modest-suit.name",
    crawlTimeStart: Long(1651994478734),
    crawlTimeEnd: Long(1673949960809),
    status: "failed",
    sitesCrawled: 88651,
    links: [
      "http://jumbo-connotation.name",
      "http://taut-pasta.info",
      "https://mountainous-indigence.com",
    ],
    title: "dolor enim sequi",
  },
  {
    ownerId: ObjectId("6ebbc10fec0aac198b4a53b2"),
    groupId: 23696,
    root: true,
    url: "http://steep-calico.com",
    crawlTimeStart: Long(1641320426260),
    crawlTimeEnd: Long(1679001807225),
    status: "success",
    sitesCrawled: 60285,
    links: [
      "https://well-documented-excellence.biz",
      "https://unequaled-evaporation.name",
      "http://superior-boy.info",
      "http://vivid-substance.org",
      "http://shameful-feeding.info",
      "http://outstanding-contention.org",
    ],
    title: "molestias magnam ipsa",
  },
  {
    ownerId: ObjectId("ea055b1732be8c42fe1169cc"),
    groupId: 32368,
    root: false,
    url: "http://useful-buffalo.com",
    crawlTimeStart: Long(1642237292701),
    crawlTimeEnd: Long(1685402976062),
    status: "running",
    sitesCrawled: 40643,
    links: [
      "https://celebrated-reactant.com",
      "http://far-flung-calculation.net",
      "https://unsightly-conception.biz",
      "https://pricey-karate.com",
      "https://back-estuary.biz",
      "http://anguished-volcano.net",
      "http://smooth-west.org",
      "https://rural-council.net",
    ],
    title: "nulla earum quae",
  },
  {
    ownerId: ObjectId("efe8536a35ada5c9a6be87c1"),
    groupId: 38004,
    root: true,
    url: "http://ringed-puppet.org",
    crawlTimeStart: Long(1657964090831),
    crawlTimeEnd: Long(1684322362189),
    status: "failed",
    sitesCrawled: 24119,
    links: [
      "https://glittering-resolution.info",
      "http://aching-inn.org",
      "http://joyful-questioner.org",
      "https://unsightly-form.net",
      "http://youthful-cesspool.info",
      "http://little-locality.info",
      "https://illiterate-crawdad.net",
      "https://knobby-ravioli.org",
      "https://alienated-extent.biz",
    ],
    title: "atque ipsam magnam",
  },
  {
    ownerId: ObjectId("f0ad3a31bec249ad0bff8cab"),
    groupId: 58365,
    root: true,
    url: "https://lucky-investigator.com",
    crawlTimeStart: Long(1645489595121),
    crawlTimeEnd: Long(1674600797956),
    status: "failed",
    sitesCrawled: 1457,
    links: [
      "http://vibrant-breastplate.net",
      "https://oily-ascend.net",
      "https://silly-sake.info",
      "http://near-fuel.name",
      "https://cavernous-comradeship.net",
      "http://crushing-teammate.name",
      "https://critical-palace.org",
      "http://uneven-sonata.org",
    ],
    title: "ex sunt voluptates",
  },
  {
    ownerId: ObjectId("983e1706bd033107ca48448a"),
    groupId: 79447,
    root: true,
    url: "https://weak-gambling.com",
    crawlTimeStart: Long(1671320959589),
    crawlTimeEnd: Long(1682171823259),
    status: "failed",
    sitesCrawled: 83519,
    links: [
      "http://awesome-presidency.name",
      "https://extroverted-transcript.name",
      "https://forsaken-governor.info",
    ],
    title: "minus blanditiis alias",
  },
  {
    ownerId: ObjectId("adbc78dd98fc0caed24ed71f"),
    groupId: 57805,
    root: true,
    url: "http://unwieldy-story-telling.net",
    crawlTimeStart: Long(1666309768162),
    crawlTimeEnd: Long(1692413534329),
    status: "running",
    sitesCrawled: 75444,
    links: ["https://well-groomed-acorn.net"],
    title: "eligendi illum omnis",
  },
  {
    ownerId: ObjectId("19b0dc5f58b8bd6da81753ba"),
    groupId: 42008,
    root: false,
    url: "http://ajar-ignorant.org",
    crawlTimeStart: Long(1665504628400),
    crawlTimeEnd: Long(1673583223604),
    status: "running",
    sitesCrawled: 54030,
    links: [
      "http://exotic-jute.net",
      "http://shimmering-spelling.info",
      "http://ignorant-optimization.org",
      "http://uncommon-critic.org",
    ],
    title: "reiciendis assumenda nesciunt",
  },
  {
    ownerId: ObjectId("970526aebfa0bc29dbf9d34e"),
    groupId: 9307,
    root: false,
    url: "http://truthful-literature.net",
    crawlTimeStart: Long(1645151890633),
    crawlTimeEnd: Long(1675196789251),
    status: "success",
    sitesCrawled: 96385,
    links: ["https://helpless-photo.name", "https://variable-panties.com"],
    title: "totam atque libero",
  },
  {
    ownerId: ObjectId("cebb82fdcff8ebe2d0b8ab33"),
    groupId: 24826,
    root: false,
    url: "https://polished-eggplant.name",
    crawlTimeStart: Long(1644233335450),
    crawlTimeEnd: Long(1678430401114),
    status: "success",
    sitesCrawled: 84467,
    links: [
      "https://sophisticated-turtle.net",
      "http://worrisome-atelier.biz",
      "https://bright-beanie.biz",
      "https://blaring-stay.org",
    ],
    title: "non illum suscipit",
  },
  {
    ownerId: ObjectId("93cac6fcedda5d9f42f7c6fb"),
    groupId: 79059,
    root: true,
    url: "https://formal-upgrade.org",
    crawlTimeStart: Long(1662298200920),
    crawlTimeEnd: Long(1673866326821),
    status: "running",
    sitesCrawled: 6044,
    links: [],
    title: "quasi nobis mollitia",
  },
  {
    ownerId: ObjectId("2ecbc556ce7d59ad0206a0eb"),
    groupId: 63308,
    root: true,
    url: "https://flimsy-quest.biz",
    crawlTimeStart: Long(1662370241079),
    crawlTimeEnd: Long(1675292326117),
    status: "success",
    sitesCrawled: 44929,
    links: ["http://thankful-spike.org", "http://verifiable-ringworm.info"],
    title: "et itaque nam",
  },
  {
    ownerId: ObjectId("d15fe072e790fa4c24f5f5ce"),
    groupId: 99443,
    root: false,
    url: "http://indolent-inevitable.info",
    crawlTimeStart: Long(1645671658498),
    crawlTimeEnd: Long(1682401628436),
    status: "success",
    sitesCrawled: 11927,
    links: ["https://straight-author.name", "https://live-rack.biz"],
    title: "itaque facere autem",
  },
  {
    ownerId: ObjectId("efa4f3d426adf590feffdd4e"),
    groupId: 20581,
    root: true,
    url: "http://complicated-wild.name",
    crawlTimeStart: Long(1657173271994),
    crawlTimeEnd: Long(1673292958397),
    status: "failed",
    sitesCrawled: 42417,
    links: [
      "http://afraid-churn.org",
      "https://deadly-routine.com",
      "http://massive-loincloth.org",
      "http://profitable-nightmare.com",
      "http://grumpy-cd.com",
      "http://striking-tenement.com",
    ],
    title: "odio excepturi vel",
  },
  {
    ownerId: ObjectId("ba000a6f5d0dfeab3af5558c"),
    groupId: 67316,
    root: true,
    url: "https://timely-mare.biz",
    crawlTimeStart: Long(1659566760043),
    crawlTimeEnd: Long(1680025184800),
    status: "running",
    sitesCrawled: 11306,
    links: [],
    title: "ipsa quod impedit",
  },
  {
    ownerId: ObjectId("a16ad17bcfcccfcf02fab98b"),
    groupId: 99790,
    root: false,
    url: "https://glistening-mass.name",
    crawlTimeStart: Long(1658224253825),
    crawlTimeEnd: Long(1682104021373),
    status: "running",
    sitesCrawled: 89072,
    links: [
      "http://unnatural-financing.org",
      "http://limping-petal.org",
      "http://improbable-shoe-horn.name",
      "http://electric-fail.com",
    ],
    title: "fugiat quam facere",
  },
  {
    ownerId: ObjectId("acd84a0b74dc8250dcb7a22a"),
    groupId: 2011,
    root: false,
    url: "http://fine-breadfruit.info",
    crawlTimeStart: Long(1642451081731),
    crawlTimeEnd: Long(1674988988293),
    status: "running",
    sitesCrawled: 64602,
    links: [
      "http://portly-tune.net",
      "https://rigid-shackle.info",
      "https://thorough-reward.net",
      "http://bite-sized-affinity.name",
      "https://spectacular-shoulder.biz",
      "https://superficial-hyphenation.net",
    ],
    title: "facilis est quidem",
  },
  {
    ownerId: ObjectId("6910ce30d5e7af5ee0cbc3af"),
    groupId: 24352,
    root: true,
    url: "https://jumpy-gamma-ray.org",
    crawlTimeStart: Long(1655324403752),
    crawlTimeEnd: Long(1675868350582),
    status: "failed",
    sitesCrawled: 37717,
    links: [
      "https://grizzled-procedure.org",
      "https://wonderful-bat.org",
      "https://energetic-postage.info",
      "https://elated-cymbal.info",
    ],
    title: "cupiditate odio incidunt",
  },
  {
    ownerId: ObjectId("6ccadb9d6fd7f670ccefcce2"),
    groupId: 73499,
    root: false,
    url: "http://glittering-carboxyl.name",
    crawlTimeStart: Long(1648403766156),
    crawlTimeEnd: Long(1690030176582),
    status: "running",
    sitesCrawled: 11658,
    links: ["https://hungry-environment.org"],
    title: "nisi cumque aspernatur",
  },
  {
    ownerId: ObjectId("bf4ffd91dd756dfcb99f0dc0"),
    groupId: 41811,
    root: false,
    url: "http://united-topsail.info",
    crawlTimeStart: Long(1670415247568),
    crawlTimeEnd: Long(1681603492013),
    status: "success",
    sitesCrawled: 90912,
    links: [
      "https://snoopy-waterbed.biz",
      "http://soft-decline.biz",
      "https://tight-cyclone.info",
      "http://lean-disagreement.name",
      "https://lumpy-craw.info",
      "https://necessary-whorl.org",
    ],
    title: "vel quae saepe",
  },
  {
    ownerId: ObjectId("d82f6f8eef2238ecbccecb10"),
    groupId: 49116,
    root: false,
    url: "https://handsome-limestone.info",
    crawlTimeStart: Long(1657756474844),
    crawlTimeEnd: Long(1680680481813),
    status: "failed",
    sitesCrawled: 88086,
    links: [],
    title: "exercitationem ab corrupti",
  },
  {
    ownerId: ObjectId("eacc4b1dcea10dde9686fbc9"),
    groupId: 89212,
    root: false,
    url: "http://intent-arithmetic.name",
    crawlTimeStart: Long(1653841686762),
    crawlTimeEnd: Long(1692772301589),
    status: "running",
    sitesCrawled: 81971,
    links: [
      "https://warped-detective.biz",
      "https://precious-tensor.org",
      "http://colorless-everyone.info",
      "https://weird-cornmeal.org",
      "https://content-lookout.org",
    ],
    title: "voluptas fugiat illo",
  },
  {
    ownerId: ObjectId("fb90d9d9aed6537bcd3c0f50"),
    groupId: 86138,
    root: true,
    url: "http://outrageous-depth.biz",
    crawlTimeStart: Long(1660873384197),
    crawlTimeEnd: Long(1690778586878),
    status: "failed",
    sitesCrawled: 46853,
    links: [
      "https://weird-outhouse.com",
      "http://long-beer.info",
      "https://near-armpit.name",
    ],
    title: "amet qui asperiores",
  },
  {
    ownerId: ObjectId("6dbef2bafefa6a265f4da3c6"),
    groupId: 61178,
    root: false,
    url: "http://fumbling-soldier.net",
    crawlTimeStart: Long(1642257023561),
    crawlTimeEnd: Long(1684802359798),
    status: "success",
    sitesCrawled: 63001,
    links: [],
    title: "voluptatem est eligendi",
  },
  {
    ownerId: ObjectId("691ec6bdfd7dedce46ac9d8b"),
    groupId: 90341,
    root: true,
    url: "http://super-gym.com",
    crawlTimeStart: Long(1660824602860),
    crawlTimeEnd: Long(1686609863540),
    status: "failed",
    sitesCrawled: 74812,
    links: [],
    title: "necessitatibus praesentium fugit",
  },
  {
    ownerId: ObjectId("39af22f15fc742a19b20f8b7"),
    groupId: 23681,
    root: true,
    url: "https://creepy-obesity.name",
    crawlTimeStart: Long(1643913306277),
    crawlTimeEnd: Long(1690819740836),
    status: "failed",
    sitesCrawled: 50822,
    links: ["https://fickle-cutting.name"],
    title: "illum exercitationem voluptatibus",
  },
  {
    ownerId: ObjectId("edb7c7d0ec50acdecf5dcf8c"),
    groupId: 1454,
    root: false,
    url: "https://unruly-bulldozer.info",
    crawlTimeStart: Long(1646436406898),
    crawlTimeEnd: Long(1685199028891),
    status: "success",
    sitesCrawled: 73734,
    links: [
      "https://murky-laryngitis.biz",
      "https://splendid-beet.info",
      "http://trustworthy-reflection.biz",
      "https://crooked-supper.name",
      "http://energetic-snuck.net",
      "http://green-discrimination.biz",
    ],
    title: "magni quis adipisci",
  },
  {
    ownerId: ObjectId("bb4ffaf4d6882035de2c9722"),
    groupId: 34558,
    root: false,
    url: "https://high-doorway.com",
    crawlTimeStart: Long(1650184499613),
    crawlTimeEnd: Long(1675998718470),
    status: "running",
    sitesCrawled: 7240,
    links: ["http://gullible-shelf.com", "http://dramatic-dinghy.net"],
    title: "dolores veritatis fuga",
  },
  {
    ownerId: ObjectId("0a329b3cc76aecdef69ee1ac"),
    groupId: 76219,
    root: false,
    url: "http://original-enclave.net",
    crawlTimeStart: Long(1666033897405),
    crawlTimeEnd: Long(1684324075730),
    status: "failed",
    sitesCrawled: 6127,
    links: ["https://grimy-term.name"],
    title: "laborum sunt et",
  },
  {
    ownerId: ObjectId("1e90e21abee6beda6656fd96"),
    groupId: 73046,
    root: true,
    url: "https://descriptive-increase.biz",
    crawlTimeStart: Long(1644428592543),
    crawlTimeEnd: Long(1692149521041),
    status: "success",
    sitesCrawled: 83821,
    links: [
      "http://rotating-dividend.name",
      "http://insecure-dredger.name",
      "http://shimmering-median.name",
      "https://spiffy-hammock.org",
      "https://valid-speaking.org",
      "http://irresponsible-carrot.net",
      "http://inborn-weird.biz",
      "https://windy-snap.biz",
      "http://gleaming-revival.info",
    ],
    title: "saepe provident cumque",
  },
  {
    ownerId: ObjectId("88b8daf0563cdebacba5ef47"),
    groupId: 2814,
    root: true,
    url: "http://conscious-chain.biz",
    crawlTimeStart: Long(1659900082840),
    crawlTimeEnd: Long(1680753563585),
    status: "running",
    sitesCrawled: 73115,
    links: ["http://aged-purse.com"],
    title: "optio nobis earum",
  },
  {
    ownerId: ObjectId("f8168a802bc8deeebcf8eceb"),
    groupId: 2437,
    root: true,
    url: "http://periodic-pin.name",
    crawlTimeStart: Long(1658922819922),
    crawlTimeEnd: Long(1679762266142),
    status: "running",
    sitesCrawled: 29329,
    links: ["http://elastic-validity.org"],
    title: "dolorum aperiam voluptatibus",
  },
  {
    ownerId: ObjectId("f4a33d205ebda1ad7a3e8bab"),
    groupId: 68595,
    root: false,
    url: "https://teeming-purpose.info",
    crawlTimeStart: Long(1664561574107),
    crawlTimeEnd: Long(1686830750736),
    status: "running",
    sitesCrawled: 14074,
    links: [],
    title: "alias ad perferendis",
  },
  {
    ownerId: ObjectId("bdabcd3af9adccdda472f33d"),
    groupId: 33445,
    root: false,
    url: "http://anxious-bouquet.com",
    crawlTimeStart: Long(1643504934871),
    crawlTimeEnd: Long(1678094441367),
    status: "failed",
    sitesCrawled: 22548,
    links: [],
    title: "deserunt magnam perspiciatis",
  },
  {
    ownerId: ObjectId("b149a81da73917dcd6ded1a2"),
    groupId: 79177,
    root: true,
    url: "http://snappy-seashore.biz",
    crawlTimeStart: Long(1664937500833),
    crawlTimeEnd: Long(1680859088372),
    status: "success",
    sitesCrawled: 25707,
    links: [
      "http://illustrious-drapes.info",
      "https://cooked-memorial.biz",
      "http://admired-heir.biz",
    ],
    title: "fuga illo nesciunt",
  },
  {
    ownerId: ObjectId("ccaf958afe0cbf60ccab095c"),
    groupId: 64570,
    root: false,
    url: "https://trivial-airbag.info",
    crawlTimeStart: Long(1671771221010),
    crawlTimeEnd: Long(1680858068473),
    status: "running",
    sitesCrawled: 23873,
    links: ["https://harmful-inauguration.info", "https://loose-gloom.name"],
    title: "dolores nam expedita",
  },
  {
    ownerId: ObjectId("5ac6258f66b38a214840f3a2"),
    groupId: 61042,
    root: false,
    url: "http://superb-broom.biz",
    crawlTimeStart: Long(1647919900505),
    crawlTimeEnd: Long(1689512170158),
    status: "running",
    sitesCrawled: 48394,
    links: [
      "https://those-criticism.com",
      "http://perky-jute.com",
      "http://decisive-section.org",
      "http://great-feed.net",
      "http://hollow-cirrus.name",
      "http://skinny-ignorant.com",
    ],
    title: "nihil provident voluptates",
  },
  {
    ownerId: ObjectId("0aa2eb62ced5da07e01acdb2"),
    groupId: 33701,
    root: false,
    url: "https://poised-concentrate.com",
    crawlTimeStart: Long(1651350052595),
    crawlTimeEnd: Long(1676465572804),
    status: "failed",
    sitesCrawled: 43192,
    links: [],
    title: "consectetur sequi vel",
  },
  {
    ownerId: ObjectId("ddebfdd0ffcd204bdf85efbf"),
    groupId: 34135,
    root: false,
    url: "https://outlying-space.com",
    crawlTimeStart: Long(1664977692769),
    crawlTimeEnd: Long(1685488922991),
    status: "failed",
    sitesCrawled: 11490,
    links: ["https://faithful-pumpkinseed.org"],
    title: "laboriosam eius facere",
  },
  {
    ownerId: ObjectId("06f3da1fded6ab809faf08fd"),
    groupId: 23978,
    root: true,
    url: "http://offensive-salami.info",
    crawlTimeStart: Long(1663884271755),
    crawlTimeEnd: Long(1676254018674),
    status: "success",
    sitesCrawled: 2011,
    links: ["http://joint-astrologer.biz", "https://frightening-spur.name"],
    title: "quam voluptate nostrum",
  },
  {
    ownerId: ObjectId("6eddebdfcedcf1c5092156e4"),
    groupId: 10454,
    root: false,
    url: "https://icky-rambler.info",
    crawlTimeStart: Long(1647228249865),
    crawlTimeEnd: Long(1691308082908),
    status: "success",
    sitesCrawled: 2232,
    links: [
      "https://jagged-rancher.name",
      "https://lawful-web.org",
      "http://legal-cape.info",
      "http://handmade-slice.name",
      "http://official-will.biz",
      "https://starry-swing.biz",
      "http://charming-hydrolyse.org",
      "https://elliptical-gender.org",
      "https://hungry-cirrhosis.biz",
      "http://hasty-retailer.info",
    ],
    title: "impedit vel maxime",
  },
  {
    ownerId: ObjectId("ede5f2adeabecbc3fd978cf1"),
    groupId: 78824,
    root: false,
    url: "http://frequent-pearl.com",
    crawlTimeStart: Long(1646546132700),
    crawlTimeEnd: Long(1673257509934),
    status: "running",
    sitesCrawled: 87007,
    links: [
      "https://precious-sunlight.name",
      "http://acclaimed-composer.name",
      "http://pastel-consent.net",
      "http://polished-mineshaft.org",
      "http://grim-locality.info",
    ],
    title: "alias ducimus repellat",
  },
  {
    ownerId: ObjectId("dfda50c20b1dfe0eba7dd8d3"),
    groupId: 38418,
    root: true,
    url: "https://voluminous-controversy.name",
    crawlTimeStart: Long(1661398104859),
    crawlTimeEnd: Long(1674048256478),
    status: "failed",
    sitesCrawled: 9381,
    links: [
      "https://infantile-species.biz",
      "https://outstanding-glasses.net",
      "http://severe-evaporation.org",
      "http://frightening-screenwriting.biz",
      "https://informal-handsaw.org",
      "http://pure-burglar.name",
      "https://adorable-goddess.net",
      "http://triangular-dial.biz",
    ],
    title: "eos odit quisquam",
  },
  {
    ownerId: ObjectId("960b5c0fccb0d95830ac32e9"),
    groupId: 65254,
    root: false,
    url: "https://overcooked-head.com",
    crawlTimeStart: Long(1642015602043),
    crawlTimeEnd: Long(1678273871898),
    status: "failed",
    sitesCrawled: 35352,
    links: ["http://occasional-task.name"],
    title: "enim magnam officiis",
  },
  {
    ownerId: ObjectId("5cab7e9ac7cb496ebca4f670"),
    groupId: 67050,
    root: false,
    url: "https://this-sac.net",
    crawlTimeStart: Long(1652589960085),
    crawlTimeEnd: Long(1688434182622),
    status: "success",
    sitesCrawled: 47967,
    links: [
      "https://right-viola.biz",
      "http://lost-composition.name",
      "https://rural-housewife.name",
      "http://sleepy-jack.info",
      "http://monthly-anthropology.biz",
      "https://agile-gherkin.org",
      "https://posh-poet.org",
      "http://gregarious-inevitable.org",
      "https://blissful-tog.net",
    ],
    title: "maiores omnis recusandae",
  },
  {
    ownerId: ObjectId("8fe9bdb0ac21f6277396fdea"),
    groupId: 28195,
    root: true,
    url: "http://grand-warlord.org",
    crawlTimeStart: Long(1647963906760),
    crawlTimeEnd: Long(1681062296102),
    status: "failed",
    sitesCrawled: 30400,
    links: ["https://forsaken-rethinking.org", "https://lopsided-gather.net"],
    title: "consequatur rem ducimus",
  },
  {
    ownerId: ObjectId("df6e57be60f1c272fbc94417"),
    groupId: 3528,
    root: true,
    url: "http://nimble-chassis.name",
    crawlTimeStart: Long(1670636696667),
    crawlTimeEnd: Long(1692613137199),
    status: "success",
    sitesCrawled: 41692,
    links: [
      "http://itchy-falling-out.biz",
      "http://disgusting-today.info",
      "http://respectful-troop.name",
      "http://corrupt-epee.name",
    ],
    title: "suscipit reprehenderit illo",
  },
  {
    ownerId: ObjectId("8d07ff38286b559bd33f237c"),
    groupId: 57683,
    root: false,
    url: "https://unknown-collection.name",
    crawlTimeStart: Long(1671252173584),
    crawlTimeEnd: Long(1680936082506),
    status: "failed",
    sitesCrawled: 66291,
    links: [
      "https://sizzling-earrings.biz",
      "http://required-wingman.net",
      "http://average-housewife.net",
      "http://parallel-remote.info",
    ],
    title: "nam qui eligendi",
  },
  {
    ownerId: ObjectId("fab88dfb080154cbcdcb3df6"),
    groupId: 85880,
    root: true,
    url: "https://wide-eyed-vanilla.name",
    crawlTimeStart: Long(1663176818439),
    crawlTimeEnd: Long(1691586931788),
    status: "failed",
    sitesCrawled: 18416,
    links: [
      "http://outlandish-palm.biz",
      "https://basic-stick.net",
      "https://guilty-morale.biz",
      "https://reflecting-lime.com",
    ],
    title: "reprehenderit laborum nobis",
  },
  {
    ownerId: ObjectId("8ce5b32dbf62e6efaecedbbc"),
    groupId: 9822,
    root: false,
    url: "https://immaculate-perch.com",
    crawlTimeStart: Long(1650817877501),
    crawlTimeEnd: Long(1678378555417),
    status: "success",
    sitesCrawled: 58978,
    links: [
      "http://flamboyant-lane.com",
      "http://overdue-return.net",
      "http://warm-mine.org",
      "http://cuddly-mood.biz",
      "http://unacceptable-button.name",
      "https://trusty-manner.org",
    ],
    title: "fuga soluta ipsa",
  },
  {
    ownerId: ObjectId("c8a0a9dae5ccdb0972becaee"),
    groupId: 31983,
    root: false,
    url: "http://squeaky-locker.net",
    crawlTimeStart: Long(1656938020275),
    crawlTimeEnd: Long(1680652163380),
    status: "success",
    sitesCrawled: 11582,
    links: [
      "https://rigid-inauguration.net",
      "https://deep-hatchet.biz",
      "http://immediate-mole.info",
    ],
    title: "quas enim a",
  },
  {
    ownerId: ObjectId("bead9edf4e5cefba32d3e0a2"),
    groupId: 6417,
    root: true,
    url: "https://watchful-oatmeal.biz",
    crawlTimeStart: Long(1653134592178),
    crawlTimeEnd: Long(1680248377118),
    status: "running",
    sitesCrawled: 50439,
    links: [
      "https://fitting-confectionery.name",
      "http://murky-independence.com",
      "http://memorable-casket.info",
      "https://zany-egghead.com",
      "https://stark-power.info",
      "http://brisk-birdbath.com",
    ],
    title: "explicabo molestiae similique",
  },
  {
    ownerId: ObjectId("9da2dbc59dafad24fde60ddc"),
    groupId: 20156,
    root: false,
    url: "https://jumbo-crack.name",
    crawlTimeStart: Long(1670471698815),
    crawlTimeEnd: Long(1681638691378),
    status: "running",
    sitesCrawled: 14285,
    links: [
      "http://squeaky-skunk.biz",
      "https://prickly-wampum.net",
      "http://scientific-maize.biz",
      "http://faraway-mixer.com",
    ],
    title: "exercitationem facilis nisi",
  },
  {
    ownerId: ObjectId("efadc6a6326b3c381213daf0"),
    groupId: 70690,
    root: true,
    url: "https://enchanted-size.com",
    crawlTimeStart: Long(1652953606158),
    crawlTimeEnd: Long(1683322684844),
    status: "failed",
    sitesCrawled: 9687,
    links: [
      "http://automatic-caboose.name",
      "https://gripping-loop.com",
      "https://any-harmonise.net",
      "https://spry-forte.org",
      "https://flashy-island.info",
      "http://stale-mine.name",
      "https://possible-wake.com",
    ],
    title: "unde velit amet",
  },
  {
    ownerId: ObjectId("2e8ae07e2b7fce1cb40cb0ef"),
    groupId: 9141,
    root: false,
    url: "https://plump-many.org",
    crawlTimeStart: Long(1669683574390),
    crawlTimeEnd: Long(1673761886430),
    status: "success",
    sitesCrawled: 58768,
    links: [
      "http://stained-crewmember.info",
      "http://instructive-bandwidth.info",
      "http://occasional-chrome.com",
      "http://tough-type.name",
    ],
    title: "totam nisi excepturi",
  },
  {
    ownerId: ObjectId("02ebec2f571beb859713afc0"),
    groupId: 6600,
    root: false,
    url: "http://twin-way.org",
    crawlTimeStart: Long(1641015187921),
    crawlTimeEnd: Long(1690533180930),
    status: "failed",
    sitesCrawled: 46332,
    links: [
      "https://acclaimed-rumor.name",
      "https://even-tiger.info",
      "https://salty-ravioli.name",
      "http://biodegradable-mint.info",
      "http://tired-pard.net",
      "https://blond-mankind.com",
      "http://unwitting-uniform.com",
    ],
    title: "amet debitis reiciendis",
  },
  {
    ownerId: ObjectId("cadfa7b7debb112ee32e7bfc"),
    groupId: 21600,
    root: true,
    url: "http://lone-bandanna.info",
    crawlTimeStart: Long(1651911576701),
    crawlTimeEnd: Long(1687670425422),
    status: "success",
    sitesCrawled: 48350,
    links: [],
    title: "recusandae nihil incidunt",
  },
  {
    ownerId: ObjectId("6efc9fa9d009c121cce5cc31"),
    groupId: 5936,
    root: true,
    url: "http://salty-sword.org",
    crawlTimeStart: Long(1644797768186),
    crawlTimeEnd: Long(1683335864768),
    status: "success",
    sitesCrawled: 51184,
    links: [
      "http://proud-tree.name",
      "https://obese-hiking.biz",
      "http://secondary-honoree.com",
      "https://dreary-rhythm.org",
      "https://lovely-lox.info",
      "http://fruitful-chain.biz",
      "https://another-frown.biz",
    ],
    title: "ut libero debitis",
  },
  {
    ownerId: ObjectId("a1aebab20b1cfbf5fcfafadd"),
    groupId: 64753,
    root: true,
    url: "http://cloudy-cartel.info",
    crawlTimeStart: Long(1659568355681),
    crawlTimeEnd: Long(1676353364341),
    status: "failed",
    sitesCrawled: 50185,
    links: [
      "https://female-senate.com",
      "http://angelic-joy.biz",
      "http://decent-circulation.org",
      "http://plaintive-vintage.biz",
      "http://solid-notepad.name",
      "https://average-sleepiness.name",
      "https://regular-corridor.info",
      "http://trustworthy-machine.info",
      "https://junior-supply.net",
    ],
    title: "praesentium amet facilis",
  },
  {
    ownerId: ObjectId("d50688e521eabcf3584c50d5"),
    groupId: 39723,
    root: true,
    url: "http://buttery-threat.com",
    crawlTimeStart: Long(1672321306505),
    crawlTimeEnd: Long(1686111557674),
    status: "failed",
    sitesCrawled: 82425,
    links: [
      "https://sweltering-telephone.org",
      "http://sizzling-crop.net",
      "http://snoopy-swan.org",
      "http://hoarse-perspective.com",
      "http://showy-plan.biz",
      "http://rosy-string.com",
    ],
    title: "fuga eos quo",
  },
  {
    ownerId: ObjectId("9a2aeaa15aa4ee474cb39f4b"),
    groupId: 29135,
    root: false,
    url: "http://bruised-stitch.com",
    crawlTimeStart: Long(1646876439666),
    crawlTimeEnd: Long(1676703352560),
    status: "running",
    sitesCrawled: 94935,
    links: [
      "https://tinted-average.biz",
      "https://ragged-sled.biz",
      "http://scientific-poison.biz",
      "http://broken-pecan.net",
      "https://ecstatic-cormorant.biz",
      "http://starchy-controller.net",
      "https://pushy-boy.org",
      "https://awesome-recovery.net",
      "http://dimpled-pile.biz",
    ],
    title: "dolor minima reiciendis",
  },
  {
    ownerId: ObjectId("8c7cea6ff957147bbff3f4aa"),
    groupId: 32773,
    root: true,
    url: "https://imaginative-vitro.org",
    crawlTimeStart: Long(1652535932409),
    crawlTimeEnd: Long(1685547814760),
    status: "success",
    sitesCrawled: 83507,
    links: [
      "http://antique-telephone.net",
      "http://acidic-loophole.biz",
      "http://gigantic-sweatshop.biz",
      "http://crisp-piccolo.org",
      "https://square-pianist.biz",
    ],
    title: "amet dolor quis",
  },
  {
    ownerId: ObjectId("4118579b8baa3cccd1e590af"),
    groupId: 66748,
    root: false,
    url: "https://minty-voyage.biz",
    crawlTimeStart: Long(1650810799112),
    crawlTimeEnd: Long(1685968899693),
    status: "running",
    sitesCrawled: 61978,
    links: [
      "https://boiling-walker.org",
      "https://empty-sigh.name",
      "http://monstrous-seeker.org",
    ],
    title: "fugiat sunt vitae",
  },
  {
    ownerId: ObjectId("dcb63c7babeda6e286ac6ef2"),
    groupId: 19005,
    root: true,
    url: "http://gummy-evaluator.net",
    crawlTimeStart: Long(1657782330896),
    crawlTimeEnd: Long(1692663713587),
    status: "success",
    sitesCrawled: 34299,
    links: [
      "https://limping-trailpatrol.com",
      "http://belated-lobotomy.com",
      "http://silly-amenity.info",
      "http://tedious-throat.net",
      "http://finished-reparation.name",
      "https://misguided-shallot.info",
      "http://lean-cable.org",
      "http://slow-caravan.name",
      "http://luminous-specification.org",
      "https://thorny-input.net",
    ],
    title: "voluptatibus tempora voluptate",
  },
  {
    ownerId: ObjectId("57e7fbf03902baebbedf9ee9"),
    groupId: 55022,
    root: true,
    url: "http://bland-poison.com",
    crawlTimeStart: Long(1645528155121),
    crawlTimeEnd: Long(1690776487811),
    status: "success",
    sitesCrawled: 34440,
    links: [
      "https://enormous-kingdom.info",
      "http://monthly-kettledrum.info",
      "https://quintessential-data.biz",
      "https://minor-inn.org",
      "http://revolving-squirrel.name",
      "https://sizzling-edible.net",
    ],
    title: "magni atque blanditiis",
  },
  {
    ownerId: ObjectId("51e192dbe03c8accb1ec7fdb"),
    groupId: 85416,
    root: true,
    url: "http://crowded-migrant.net",
    crawlTimeStart: Long(1654864765959),
    crawlTimeEnd: Long(1691025603503),
    status: "success",
    sitesCrawled: 98996,
    links: [
      "https://serene-crook.biz",
      "http://rigid-bush.com",
      "https://bright-clay.info",
      "http://coarse-laryngitis.org",
      "http://second-polarisation.org",
    ],
    title: "quod nisi officiis",
  },
  {
    ownerId: ObjectId("da33a5cce77addeaf79ac019"),
    groupId: 97766,
    root: true,
    url: "http://only-down.net",
    crawlTimeStart: Long(1657501701049),
    crawlTimeEnd: Long(1680594542053),
    status: "running",
    sitesCrawled: 23768,
    links: ["https://pink-goddess.org", "https://loud-ballot.org"],
    title: "provident quos laborum",
  },
  {
    ownerId: ObjectId("d215fc147fe4edb7cff72794"),
    groupId: 81876,
    root: false,
    url: "http://cumbersome-cure.info",
    crawlTimeStart: Long(1662504698062),
    crawlTimeEnd: Long(1680111654322),
    status: "running",
    sitesCrawled: 37674,
    links: [
      "http://salty-symmetry.name",
      "https://authentic-rebellion.info",
      "https://serpentine-tatami.net",
      "http://spectacular-insectarium.com",
      "http://burly-stock-in-trade.net",
      "http://strict-pattypan.net",
      "http://tangible-router.org",
      "http://avaricious-microlending.biz",
      "https://illiterate-randomisation.name",
      "http://dearest-nightlife.com",
    ],
    title: "tempora dolorum consectetur",
  },
  {
    ownerId: ObjectId("b895f3b24dab8edf66fe93cd"),
    groupId: 26176,
    root: true,
    url: "https://legal-impairment.biz",
    crawlTimeStart: Long(1645095594996),
    crawlTimeEnd: Long(1675824656202),
    status: "success",
    sitesCrawled: 7195,
    links: [],
    title: "perspiciatis modi minima",
  },
  {
    ownerId: ObjectId("ffb3cf1156c5dd5bab69ef35"),
    groupId: 844,
    root: true,
    url: "https://grumpy-tadpole.name",
    crawlTimeStart: Long(1654582980413),
    crawlTimeEnd: Long(1678504206890),
    status: "running",
    sitesCrawled: 64236,
    links: [
      "https://outrageous-skullduggery.com",
      "http://purple-burn-out.name",
      "https://burly-migration.biz",
      "http://stimulating-heavy.net",
      "https://victorious-migrant.org",
      "http://clumsy-pile.org",
      "https://jovial-cell.info",
      "http://thorny-recipe.info",
    ],
    title: "labore hic consequatur",
  },
  {
    ownerId: ObjectId("e1f7b9d556ea53f5c25f3a77"),
    groupId: 98339,
    root: false,
    url: "http://distant-catch.info",
    crawlTimeStart: Long(1667509950214),
    crawlTimeEnd: Long(1675939236818),
    status: "failed",
    sitesCrawled: 69947,
    links: [
      "http://watchful-catch.info",
      "https://yellow-currant.info",
      "https://monstrous-sentencing.net",
      "http://ecstatic-grandmom.info",
      "https://full-pound.biz",
    ],
    title: "ratione eum nesciunt",
  },
  {
    ownerId: ObjectId("b0adf66f00ae78bb91a949a1"),
    groupId: 61423,
    root: true,
    url: "http://firm-check.info",
    crawlTimeStart: Long(1668417004451),
    crawlTimeEnd: Long(1689126805525),
    status: "failed",
    sitesCrawled: 94946,
    links: [
      "http://exciting-vintage.info",
      "http://delectable-tailspin.com",
      "http://whispered-parameter.org",
      "http://attentive-puma.biz",
    ],
    title: "debitis nobis error",
  },
  {
    ownerId: ObjectId("3b9f0e59eedfafcd69c835a1"),
    groupId: 82666,
    root: false,
    url: "https://slushy-infarction.biz",
    crawlTimeStart: Long(1641407587180),
    crawlTimeEnd: Long(1679121981079),
    status: "failed",
    sitesCrawled: 99438,
    links: [
      "http://old-fashioned-boatload.org",
      "https://shocked-house.name",
      "https://brown-countess.info",
      "http://biodegradable-reservoir.info",
    ],
    title: "tenetur minima iure",
  },
  {
    ownerId: ObjectId("716d8438da49fdf22d1466af"),
    groupId: 48137,
    root: false,
    url: "https://concerned-observation.info",
    crawlTimeStart: Long(1660951385774),
    crawlTimeEnd: Long(1688707685431),
    status: "running",
    sitesCrawled: 8417,
    links: [
      "http://blank-norm.name",
      "http://enchanted-ease.name",
      "http://unsteady-trial.net",
      "http://harsh-identification.biz",
      "https://made-up-skirt.net",
    ],
    title: "id placeat harum",
  },
  {
    ownerId: ObjectId("c2fd4ac7620f7d5ece74ac9f"),
    groupId: 76180,
    root: false,
    url: "http://thorny-notion.info",
    crawlTimeStart: Long(1672411027171),
    crawlTimeEnd: Long(1678317976342),
    status: "success",
    sitesCrawled: 79446,
    links: [
      "http://classic-wax.name",
      "http://healthy-confectionery.net",
      "https://pointed-connotation.com",
      "https://worthy-relation.info",
      "http://weird-prairie.name",
      "https://intrepid-cartoon.info",
      "https://secret-platinum.com",
      "http://piercing-designer.com",
      "http://friendly-mimosa.info",
    ],
    title: "ipsum exercitationem necessitatibus",
  },
  {
    ownerId: ObjectId("6508f6ee4b26a1bdf03bfd17"),
    groupId: 1,
    root: false,
    url: "http://impeccable-job.org",
    crawlTimeStart: Long(1666383109078),
    crawlTimeEnd: Long(1688480121715),
    status: "running",
    sitesCrawled: 36399,
    links: [],
    title: "illo atque molestias",
  },
  {
    ownerId: ObjectId("6508f6ee4b26a1bdf03bfd17"),
    groupId: 1,
    root: true,
    url: "https://rusty-vitamin.info",
    crawlTimeStart: Long(1650891736544),
    crawlTimeEnd: Long(1692116308686),
    status: "running",
    sitesCrawled: 81411,
    links: [
      "http://polished-corn.com",
      "http://hopeful-nondisclosure.name",
      "http://serious-tilt.com",
      "http://elaborate-guava.biz",
      "http://agreeable-earth.info",
      "https://keen-disclaimer.net",
      "http://intelligent-shock.info",
    ],
    title: "necessitatibus numquam adipisci",
  },
  {
    ownerId: ObjectId("6508f6ee4b26a1bdf03bfd17"),
    groupId: 2,
    root: true,
    url: "http://kosher-curse.net",
    crawlTimeStart: Long(1646591079339),
    crawlTimeEnd: Long(1684492507400),
    status: "success",
    sitesCrawled: 2459,
    links: [
      "https://interesting-normalisation.com",
      "http://yearly-faith.org",
      "https://eager-root.net",
      "http://familiar-foxglove.name",
      "http://excellent-snowplow.biz",
      "https://misguided-siding.com",
      "http://separate-blade.net",
      "https://average-cast.com",
    ],
    title: "et enim facilis",
  },
  {
    ownerId: ObjectId("6508f6ee4b26a1bdf03bfd17"),
    groupId: 2,
    root: false,
    url: "https://rigid-certification.biz",
    crawlTimeStart: Long(1646445283280),
    crawlTimeEnd: Long(1675145258668),
    status: "failed",
    sitesCrawled: 96149,
    links: [
      "https://sparse-digestion.name",
      "http://incomparable-semester.info",
      "https://long-term-slang.info",
      "http://oily-wrecker.net",
      "https://dutiful-passport.name",
      "https://frozen-rear.info",
      "http://immaculate-print.info",
      "https://thankful-sousaphone.com",
      "http://yellowish-cranky.org",
      "http://murky-bribery.name",
    ],
    title: "quidem earum inventore",
  },
  {
    ownerId: ObjectId("6508f6ee4b26a1bdf03bfd17"),
    groupId: 2,
    root: true,
    url: "https://deafening-ammunition.com",
    crawlTimeStart: Long(1652344788054),
    crawlTimeEnd: Long(1681858663277),
    status: "running",
    sitesCrawled: 61014,
    links: ["https://tragic-newsprint.info", "http://heavenly-fortnight.name"],
    title: "assumenda est rem",
  },
]);
